[global]
workgroup = WORKGROUP
server string = LibraryIT Server
security = user
map to guest = never

[ebooks]
path = /libraryit/ebooks
browseable = yes
read only = no
valid users = contributor librarian

[papers]
path = /libraryit/papers
browseable = yes
read only = no
valid users = contributor librarian

[sourcecode]
path = /libraryit/sourcecode
browseable = yes
read only = yes
valid users = member contributor librarian

[docs]
path = /libraryit/docs
browseable = yes
read only = no
valid users = member contributor librarian
write list = librarian
