[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   log file = /var/log/samba/log.smbd
   max log size = 5000
   logging = file

[ebooks]
   path = /libraryit/ebooks
   browseable = yes
   read only = no
   valid users = @staff
   write list = @staff
   create mask = 0770
   directory mask = 0770

[papers]
   path = /libraryit/papers
   browseable = yes
   read only = no
   valid users = @staff
   write list = @staff
   create mask = 0770
   directory mask = 0770

[sourcecode]
   path = /libraryit/sourcecode
   browseable = yes
   read only = yes
   valid users = @readonly

[docs]
   path = /libraryit/docs
   browseable = yes
   read only = yes
   valid users = @readonly, @staff
   write list = librarian
   create mask = 0770
   directory mask = 0770
